### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by galizhan** [divis1969/android_device_meizu_meilan2#109]
Лагает при соединении через bluetooth и звук выходит из телефона

**Comment by galizhan** [comment]
И еще когда выключатель а2dp тогда не лагает но звука соответственно нету в наушниках

**Comment by ygorigor** [comment]
здесь  olegsvs исправил этот баг https://github.com/olegsvs/android_device_meizu_meilan2/commit/7117e4db759d2db66a53f4b48c9579790bd7fa98

**Comment by olegsvs** [comment]
Еще здесь https://github.com/olegsvs/android_vendor_meizu_meilan2/commit/77b890db63b0454a8f1d3717582218591e21f400

**Comment by galizhan** [comment]
извините забыл добавить что я писал про **Lineage** os

**Comment by divis1969** [comment]
A2DP поправлено в los-14.1-meilan2-v0.4
Коммиты
https://github.com/divis1969/android_device_meizu_meilan2/commit/ac63fb55e9a5948d58eebd6470a43fefe812f0d6
https://github.com/divis1969/android_vendor_meizu_meilan2/commit/da330674c1dc271b183dc2995ad08d62a92cd11e
