### ISSUE TITLE
A problem on meizupshelper

### ISSUE THREAD

**Issue by KevinMX** [divis1969/android_device_meizu_meilan2#113]
Tried to use it on meizu m2note(running los14.1) but cannot make it autorun at boot. Also tried to add meizupshelper.rc but did not work. 
thx!

**Comment by divis1969** [comment]
Did you define SELinux domain for it? Take a look at https://github.com/divis1969/android_device_meizu_meilan2/blob/cm-14.1-meilan2/sepolicy/meizupshelper.te

**Comment by KevinMX** [comment]
Got it. Going to try it out this weekend:)
How about make a flashable patch via twrp?
@Moyster Try this out!

**Comment by divis1969** [comment]
Is it ok to close this issue (since I'm not supporting M2Note)?

**Comment by ghost** [comment]
Yes, thanks for the confirmation, I told kevinMX already on Hgouts, dunno why he didn't try better than posting here but oh well... I guess it doesn't autoboot if it lacks a selinux domain, right ?

**Comment by alex-msk-dev** [comment]
KevinMX, Hi, I want to contact you, to know how to change Secro.img to unlock Meizu ? how can I contact you?
