### ISSUE TITLE
[FR] add substratum support

### ISSUE THREAD

**Issue by agent-007** [divis1969/android_device_meizu_meilan2#124]
https://forum.xda-developers.com/apps/substratum/reference-lineageos-substratum-support-t3580276

**Comment by divis1969** [comment]
Great, I'll try to follow these instructions.
Thanks!

**Comment by MASTERGUY** [comment]
:) thanks bro i also want same 😁

**Comment by divis1969** [comment]
Done https://github.com/divis1969/android_device_meizu_meilan2/releases/tag/los-14.1-oms-meilan2-v0.1

**Comment by agent-007** [comment]
works fine.
