### ISSUE TITLE
Video playback bugs still there (fixed in other devices and ported roms Like RR 5.8.3 )

### ISSUE THREAD

**Issue by MASTERGUY** [divis1969/android_device_meizu_meilan2#128]
HDR and flashed is fixed for other devices based on 3.10.65 mt6735 can be fixed on this OS?
said by vasiliy.ivanov

here

http://4pda.ru/forum/index.php?showtopic=815078&view=findpost&p=60919078

thanks 

also youtube not works

**Comment by EarsKilla** [comment]
try use og youtube, or fixes [from this thread](http://4pda.ru/forum/index.php?showtopic=715935&st=2340#entry53427521)

**Comment by MASTERGUY** [comment]
OG Youtube don't work too same if i use video patches then it turn black

**Comment by MASTERGUY** [comment]
fixed that issue thanks 4pda :)
