### ISSUE TITLE
open livedesplay,mobile phone is not smooth

### ISSUE THREAD

**Issue by hesier** [divis1969/android_device_meizu_meilan2#13]
sorry,my english is very poor…

**Comment by janengelmohr** [comment]
That's likely because libui.so isn't compiled but used pre-built. Compiling from source could fix it but when you need MTK's addons again...

**Comment by janengelmohr** [comment]
Could you tell me how you fixed it?

**Comment by divis1969** [comment]
is it question for me? I did not yet fixed it. Submitter just closed it, but opened new one: https://github.com/divis1969/android_device_meizu_meilan2/issues/24

**Comment by divis1969** [comment]
@visi0nary, what do you mean by "but when you need MTK's addons again..."? what are those addons in libui?
