### ISSUE TITLE
A2DP

### ISSUE THREAD

**Issue by bvndls** [divis1969/android_device_meizu_meilan2#135]
Когда я подключаюсь к любой BT аудиосистеме (наушники, машина и т.д.) всё происходит нормально, но как только я ставлю музыку/открываю видос на YT ничего не происходит, но через секунд 5-8 всё начинает работать, НО если я остановлю видео/музыку и посижу так секунд 7, а потом поставлю опять, начинаются дикие лаги, то же самое может вызвать звонок, например.

When I'm trying to connect to any BT audio system (headphones, car etc.) it's ok, but when I'm putting on the music or opening any YT video, nothing happens, but after 5-8 seconds it starts working, BUT if I'll stop it and wait for ~7 seconds, and put it again, it starts lagging, also a call can cause this.

Такое происходит на любой 7.1.2-прошивке, на флайме и миюае всё ок.

That's happening on any 7.1.2 based ROM, on Flyme or MIUI everything is ok.

**Comment by EarsKilla** [comment]
у меня только viper4android не меняет звук bt наушников

only viper4android does not change sound on bt headphones

**Comment by bvndls** [comment]
@EarsKilla
Всм?
То есть, если накатить вайпер, то проблема пропадёт?

**Comment by EarsKilla** [comment]
@c0ntroleverything ну без него не чекал, подсказать не смогу, но у меня само аудио игралось на арнитуре, но не обрабатывалось випером (именно по блюту). Но мб ещё из-за ревизий такое, так что не факт даже, что поможет, но попробовать можешь на свой страх и риск...
