### ISSUE TITLE
Проблема с видео - звук есть, видео нет. 

### ISSUE THREAD

**Issue by Shady885** [divis1969/android_device_meizu_meilan2#15]
Найдено на v0.3

**Comment by divis1969** [comment]
Shady885, нельзя ли приаттачить сюда видео, которое не играет?

**Comment by Shady885** [comment]
К сожалению я их уже удалил. Могу только сказать, что эти видео были сняты с беты flyme 5 на фронтальную камеру!

**Comment by divis1969** [comment]
Я думаю, что это проблема пофикшена в v0.4.
Если есть возможность - проверьте, пожалуйста.

**Comment by Shady885** [comment]
Пофиксено
