### ISSUE TITLE
Телефон делает вид, что не видит симкарту ни одном из слотов

### ISSUE THREAD

**Issue by romakov** [divis1969/android_device_meizu_meilan2#20]
Проблема в том, что устройство пишет, что не видит симкарту ни в первом, ни во втором слоте. Тестировалось на симкартах Киевстар, Life и Vodafone (МТС Украина). Но при том, когда я на горячую извлекаю симкарту он говорит, что симкарта была извлечена/добавлена и требуется перезагрузка устройства. Включение/выключения авиа режима не помогает. Голосовые звонки приходят и выполняются. USSD запросы не работают

**Comment by DevKP** [comment]
Тоже самое. МТС Украина.

**Comment by divis1969** [comment]
Снять логи можете?

**Comment by romakov** [comment]
Логи снять через ADB или как?

**Comment by divis1969** [comment]
Да.
Если на линуксе, то можно вот так:
`i=0;while true; do adb logcat -v threadtime -b all | tee logcat$i.log; ((i++)); done`

На винде тоже можно bat/cmd наверное сделать
Просто при старте он два-три раза отваливается от adb.
Можно вручную, только менять имя файла при следующем запуске (например, цифру 0):
`adb logcat -v threadtime -b all > logcat0.log`

Логи нужны со старта телефона после прошивки (с вайпом)

**Comment by romakov** [comment]
На винде не хочет. Нужно попоробовать на Linux попозже. Поставлю Mint чуть позже и скину лог

**Comment by divis1969** [comment]
на v0.5 должно все работать с симками.
можете проверить?

**Comment by romakov** [comment]
@divis1969 все работает

**Comment by rescuer812** [comment]
MT6735 meizu m2 mini не видит обе сим карты .imei не прописывает
