### ISSUE TITLE
Не разблокирует симкарты с PIN кодом

### ISSUE THREAD

**Issue by romakov** [divis1969/android_device_meizu_meilan2#21]
Не предлагает разблокировать карту, если на ней установлена блокировка. Возможно это решить проблему с USSD и определением симкарт в целом

**Comment by divis1969** [comment]
Это не работало с двумя симками? Я попробовал на v0.4 - вроде все показывает и разблокирует.
Но у меня одна симка.

**Comment by divis1969** [comment]
@romakov , на v0.5 можете проверить?

**Comment by romakov** [comment]
@divis1969 , проверил. Всё работает.
