### ISSUE TITLE
No Tethering and portable hotspot

### ISSUE THREAD

**Issue by hesier** [divis1969/android_device_meizu_meilan2#23]
Mobile network cannot be shared

**Comment by janengelmohr** [comment]
This should fix it: https://github.com/visi0nary/android_device_elephone_p8000/commit/f6b36a75e7fb805d9dee65af5469c13b2bb97e3f

Also this patch is needed: https://github.com/visi0nary/android_device_elephone_p8000/blob/cm-12.1/patches/system_netd/0001-hotpost-fix.patch

**Comment by divis1969** [comment]
Thanks, I've grabbed both.
Should be now fixed on v0.6 though I did not test data path.

**Comment by divis1969** [comment]
Ok, I'm closing if there is no objections
