### ISSUE TITLE
video

### ISSUE THREAD

**Issue by basiq1337** [divis1969/android_device_meizu_meilan2#25]
Youtube video doesnt working

**Comment by divis1969** [comment]
Fixed in v0.5
https://github.com/divis1969/android_device_meizu_meilan2/commit/59626e51144ef45e2d719b500a67ccd4ac76c4fc
https://github.com/divis1969/android_vendor_meizu_meilan2/commit/ebb77e9e86b6a4cd75dba2224b34f79190240839
