### ISSUE TITLE
sensors

### ISSUE THREAD

**Issue by basiq1337** [divis1969/android_device_meizu_meilan2#27]
Gyroscope, compas and Hall's sensor doesnt work

**Comment by divis1969** [comment]
Fixed in v0.5
https://github.com/divis1969/android_device_meizu_meilan2/commit/c716fc5f0c1f71019a555b78657ab90b6f3807f7
https://github.com/divis1969/android_vendor_meizu_meilan2/commit/692fbde973a9ec614d4194bd89f87eb542a65a7f
