### ISSUE TITLE
When turning on " Only Charging" returnig back to "MTP" stop working

### ISSUE THREAD

**Issue by basiq1337** [divis1969/android_device_meizu_meilan2#31]

**Comment by l33tnoob** [comment]
In init.mt6735.usb.rc find `#34.USB Charging Only configuration` section and chage it to following code
#34.USB Charging Only configuration
on property:sys.usb.config=charging
    stop adbd
    write /sys/class/android_usb/android0/enable 0
    write /sys/class/android_usb/android0/idVendor ${sys.usb.vid}
    write /sys/class/android_usb/android0/idProduct 2008
    write /sys/class/android_usb/android0/functions mtp
    write /sys/class/android_usb/android0/enable 1
    setprop sys.usb.state ${sys.usb.config}

**Comment by divis1969** [comment]
@ariafan, this is essentially the same config as original mtp but with different VID.
So, the user could be confused.
I'll most likely take an another way.
Thanks, anyway!

**Comment by l33tnoob** [comment]
You should remove cmode changing from init.mt6735.usb.rc. I yesterday tested this fix on 6753 platform. Your charge mode now:
#34.USB Charging Only configuration
on property:sys.usb.config=charging
    setprop sys.usb.state ${sys.usb.config}
    setprop sys.usb.charging yes

on property:sys.usb.charging=yes
    write /sys/class/android_usb/android0/enable 0
    write /sys/class/android_usb/android0/idVendor ${sys.usb.vid}
    write /sys/class/android_usb/android0/idProduct 2008
    write /sys/class/android_usb/android0/functions mtp
    write /sys/class/android_usb/android0/enable 1
    write /sys/devices/platform/mt_usb/cmode 2

on property:sys.usb.charging=no
    write /sys/devices/platform/mt_usb/cmode 1

Fixed version i show above

**Comment by divis1969** [comment]
Fixed on v0.7
https://github.com/divis1969/android_device_meizu_meilan2/commit/5e1ac99b944e6899484757649892d05a71268ef0
https://github.com/divis1969/android_packages_apps_Settings/commit/cf2c4d02ee3a4b73eb6ca340867bcbac61fc45e2
