### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by Shady885** [divis1969/android_device_meizu_meilan2#32]
При попытке отправить файл пишет В приложении "Передача по bluetooth" произошла ошибка. V0.5

**Comment by divis1969** [comment]
С чем законнекчен был (другой телефон?) и каким приложением пытались передать?

**Comment by Shady885** [comment]
Galaxy s3 тоже на неофициальном CM 12.1, пытался передать картинку из галереи.

**Comment by divis1969** [comment]
Проверьте пожалуйста на 0.7
Хотя сегодня я обнаружил, что передача на wileyfox swift с cm12.1 хоть и не крешится, но файл не отправляется.
Но с другими телефонами работало.

**Comment by Shady885** [comment]
На v0.7 файл отправился без проблем. Спасибо!

**Comment by divis1969** [comment]
Fixed on v0.7
https://github.com/divis1969/android_packages_apps_Bluetooth/commit/c2490d6ed74732b43c58bd26b1aa5415f5a2b982
https://github.com/divis1969/android_hardware_libhardware/commit/ca47327b8a6c84ae000ca29e3ccf7b2290510d0b
https://github.com/divis1969/android_external_bluetooth_bluedroid/commit/b1993d33d0e8b80c2319f01da12dbf070a4fede5
