### ISSUE TITLE
LTE  lidentified only after first boot.

### ISSUE THREAD

**Issue by Litvick** [divis1969/android_device_meizu_meilan2#33]
При первом запуске система находит LTE выбирает его по умолчанию. После переключения режима на 3g вручную (пункт LTE отсутствует) LTE пропадает.

**Comment by divis1969** [comment]
Fixed on v0.7
https://github.com/divis1969/android_device_meizu_meilan2/commit/b353f1afd277ec5716ad1782b0665f23d46243d4
