### ISSUE TITLE
Музыка не играет через bluetooth-наушники

### ISSUE THREAD

**Issue by dkova** [divis1969/android_device_meizu_meilan2#34]
У меня есть наушники Syllable G600. Подключается отлично - и телефон, и наушники показывают, что подключение успешно. Галочки HSP/HFP и A2DP в информации о подключении стоят. Включаю музыку в любом приложении - звук идёт только через динамик. К сожалению, логи приложить не могу.

**Comment by divis1969** [comment]
Проверьте на v0.6
Осталась пока еще проблема с некоторыми устройствами, но она касается pairing, а не аудио потока

**Comment by dkova** [comment]
Спасибо, работает!
