### ISSUE TITLE
Проблемы с Bluetooth

### ISSUE THREAD

**Issue by grozahn** [divis1969/android_device_meizu_meilan2#37]
Не сопряжаются устройства и требует PIN код с 16 цифр, вылетает приложение "Передача по Bluetooth" при каждой попытке передать файл.

**Comment by Shady885** [comment]
Эта тоже есть https://github.com/divis1969/android_device_meizu_meilan2/issues/32

**Comment by divis1969** [comment]
Я тоже видел ошиибку с 16 цифрами. Пусть будет отдельной багой.

**Comment by divis1969** [comment]
Закрываю эту багу, поскольку еще есть https://github.com/divis1969/android_device_meizu_meilan2/issues/47 про ту же самую проблему
