### ISSUE TITLE
Проблема после активации модуля Lucky Patcher в Xposed

### ISSUE THREAD

**Issue by grozahn** [divis1969/android_device_meizu_meilan2#39]
После активации модуля указанного выше, и после ребута, постоянно вылетает ошибка в приложении Bluetooth и кнопка Restart, после нажатия которой опять вылетает та же ошибка. Решается отключением модуля, но хочется юзать модуль чтобы не патчить каждое приложение.

**Comment by divis1969** [comment]
что этот модуль делает? Вообще говоря, если он что-то там подменяет, то проблема возможно в нем?
Я планирую в след. версии исправить в блютуз ошибку передачи файлов, проверите на ней, будет ли ваша ошибка все еще присутствовать.

Кроме того, укажите, пожалуйста, откуда вы берете xposed.

**Comment by grozahn** [comment]
Xposed с xda developers, последняя 80 версия под sdk22. Сам модуль заменяет гугловский In-App, на свой который не требует интернета и выполняет обход оплаты. В описании модуля написано что он повторяет патчи Android+.

**Comment by grozahn** [comment]
Извените за оффтоп, но я хочу спросить обновляется прошивка по ОТА или нет.

**Comment by divis1969** [comment]
нет

**Comment by divis1969** [comment]
Проверьте, пожалуйста, на v0.7, проблема все еще воспроизводится или нет?

**Comment by grozahn** [comment]
Извините но я откатился на Flyme 5

**Comment by divis1969** [comment]
пофиксилось или что?

**Comment by grozahn** [comment]
Нет, просто забыл на проблему.

**Comment by divis1969** [comment]
Я получил лог с этой (или похожей проблемой), поэтому, наверное можно и пофиксить.

Креш вот такой:

```
04-16 09:04:04.816  1297  1297 E AndroidRuntime: FATAL EXCEPTION: main
04-16 09:04:04.816  1297  1297 E AndroidRuntime: Process: com.mediatek.bluetooth, PID: 1297
04-16 09:04:04.816  1297  1297 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/MtkBt/MtkBt.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libextadvanced_jni.so"
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at java.lang.Runtime.loadLibrary(Runtime.java:366)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at java.lang.System.loadLibrary(System.java:988)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at com.mediatek.bluetooth.AdvancedService.<clinit>(AdvancedService.java:140)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at java.lang.Class.classForName(Native Method)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at java.lang.Class.forName(Class.java:309)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at java.lang.Class.forName(Class.java:273)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at com.mediatek.bluetooth.BluetoothApplication.startService(BluetoothApplication.java:171)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at com.mediatek.bluetooth.BluetoothApplication.onCreate(BluetoothApplication.java:101)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4593)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:729)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at android.app.ActivityThread.handleBindApplication(<Xposed>)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at android.app.ActivityThread.access$1600(ActivityThread.java:154)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:135)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5294)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Method.java:372)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
04-16 09:04:04.816  1297  1297 E AndroidRuntime:    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)


```

Приложение MtkBt.apk вообще не используется (иначе бы оно всегда крешилось), поэтому, я думаю, я его просто удалю из билда и проблема исчезнет.

**Comment by nasirdavinci** [comment]
мой cm12.1 не может даже загрузиться после установки и включения Xposed модуль

**Comment by divis1969** [comment]
@nasirdavinci , это что-то у вас локально, скорее всего. Потому что много от кого слышал, что сам-то xposed вроде без проблем ставится, а вот при активации некоторых модулей - вылетал блютуз.

Если можете снять лог - снимите и пришлите мне. Я сам, думаю, что xposed ставить не буду. Хочу отметить, что например, сам CM не принимает никакие баги, если на телефоне установлен xposed. Я бывает, разбираюсь, потому что думаю, что они могут показывать какие-то проблемы именно в моей прошивке.

**Comment by divis1969** [comment]
Исправлено коммитами:
https://github.com/divis1969/android_device_meizu_meilan2/commit/4f69aab4b8369ec06a8ec8b1aeca02fb4ff8b226
https://github.com/divis1969/android_vendor_meizu_meilan2/commit/2d8e91410a43a71c460b16a98824685129d50255
