### ISSUE TITLE
sdcard r/w error

### ISSUE THREAD

**Issue by pr1zralll** [divis1969/android_device_meizu_meilan2#41]
some apps crash when using sdcard
for example:
vk audio sync
etc.

**Comment by divis1969** [comment]
Can you provide a link to the app?
Do you mean external sdcard or internal?
If external, was it already formatted before or you format it with CM?
Which format it uses?

**Comment by pr1zralll** [comment]
_Can you provide a link to the app?_
http://4pda.ru/forum/index.php?showtopic=633105
http://4pda.ru/forum/index.php?showtopic=299226
_Do you mean external sdcard or internal?_
external
_If external, was it already formatted before or you format it with CM?_
i don`t know
in recovery TWRP or in CM
than format by pc
_Which format it uses?_
fat32

............
and i found some interesting, maybe it can help

apps can see 3 devices
sdcard0
sdcard1
emulated/0

sdcard0 and emulated/0 is identical

Will CM have *battery fix *(discharge 20% to 1% in 1 minute)?

2016-03-22 23:50 GMT+02:00 divis1969 notifications@github.com:

**Comment by janengelmohr** [comment]
This should fix it: https://github.com/visi0nary/android_device_elephone_p8000/commit/342c27c353b4221c3da3f0804b7e973caa05d2c1

**Comment by janengelmohr** [comment]
This is the important line: https://github.com/visi0nary/android_device_elephone_p8000/commit/342c27c353b4221c3da3f0804b7e973caa05d2c1#diff-2f3b2398af1e05dab5f3bb3d1d89e059R73

**Comment by divis1969** [comment]
@pr1zralll , is there any apps showing similar behavior (crash) but which does not require VK account?
Can you collect logs for a crash?

**Comment by divis1969** [comment]
@pr1zralll, could you please check the issue on v0.8? There was a commit related to external sdcard, it would be great to check whether it affects (fixes, perhaps!) the issue.

**Comment by pr1zralll** [comment]
it works.

**Comment by divis1969** [comment]
Ok, looks like this https://github.com/divis1969/android_device_meizu_meilan2/commit/f92046a312c208514b98b5ba503322694da3c9b5 fixed the issue. Closing it now.
