### ISSUE TITLE
Некорректно работают нотификации при включении сокрытия личной информации

### ISSUE THREAD

**Issue by agent-007** [divis1969/android_device_meizu_meilan2#42]
Как воспроизвести:
- настройки - уведомления - на заблокированном экране - скрыть личную информацию;
- настройки - экран блокировки - блокировка экрана - pin код;
- начать установку приложения из play market;
- заблокировать экран;
- дождаться установки приложения, на экране блокировки появится нотификация;
- разблокировать экран;
- вытянуть шторку с уведомлениями.

Текущее поведение:

Уведомление в шторке отображается, но текст уведомление скрыт. Стандартными способами убрать это уведомление из шторки невозможно, только тапнуть по нему для перехода в приложение. 

Ожидаемое поведение:

Уведомление в шторке должно отображаться полностью. Должна быть возможность убрать уведомление из шторки стандартными способами (смахнуть, нажать кнопку "убрать все").

**Comment by divis1969** [comment]
Отличное описание!

По баге - это не поведение CM (или AOSP) "из коробки"? 
я просто пока не могу предположить, какие косяки в порте могут приводить к такому поведению.

**Comment by agent-007** [comment]
Про CM не знаю, а AOSP себя ведёт ожидаемо, т.е. работает корректно.

**Comment by divis1969** [comment]
Я посмотрел сейчас на телефоне с aosp - там есть еще одна опция при выборе варианта показа на заблокированном экране - "hide sensitive notification content". На этом порте ее нет в меню, но видимо работает как раз так. Буду искать почему так.

**Comment by divis1969** [comment]
Мне кажется, или на v0.9 это пофикшено? По-моему, я видел какие-то коммиты на эту тему, которые подтянуты при мерже...

**Comment by agent-007** [comment]
Да, в 0.9 работает.
