### ISSUE TITLE
Не устанавливаются приложения из Google Play

### ISSUE THREAD

**Issue by agent-007** [divis1969/android_device_meizu_meilan2#43]
В частности, ABBYY textgrabber. 

Лог:

I/Finsky  ( 2376): [1] com.google.android.finsky.download.DownloadBroadcastReceiver.a(45): Intent received at DownloadBroadcastReceiver
I/Finsky  ( 2376): [1] com.google.android.finsky.download.x.b(404): com.abbyy.mobile.textgrabber.full: onProgress 20919975/20919975 Status: 200.
I/Finsky  ( 2376): [1] com.google.android.finsky.download.e.a(244): com.abbyy.mobile.textgrabber.full from 2 to 3.
I/Finsky  ( 2376): [1] com.google.android.finsky.download.x.b(603): com.abbyy.mobile.textgrabber.full: onComplete
I/Finsky  ( 2376): [1] com.google.android.finsky.download.x.i(344): Download com.abbyy.mobile.textgrabber.full removed from DownloadQueue
I/installd(  276): free_cache(0) avail 2000814080
I/Finsky  ( 2376): [1] com.google.android.finsky.receivers.v.c(24906): Prepare to copy com.abbyy.mobile.textgrabber.full (com.abbyy.mobile.textgrabber.full) from content://downloads/my_downloads/97 (expect 20919975 bytes, isGzipped: false)
E/Finsky  ( 2376): [204] com.google.android.finsky.installer.v.a(379): Can't open session for com.abbyy.mobile.textgrabber.full
W/Finsky  ( 2376): [204] com.google.android.finsky.receivers.y.a(2947): IOException while copying com.abbyy.mobile.textgrabber.full (com.abbyy.mobile.textgrabber.full): java.io.IOException
E/Finsky  ( 2376): [1] com.google.android.finsky.receivers.y.onPostExecute(4028): Error while copying download for com.abbyy.mobile.textgrabber.full (com.abbyy.mobile.textgrabber.full). isExternal=false isGzip=false

**Comment by agent-007** [comment]
Проблема, судя по всему, связана с наличием карты SD. Обычно такую проблему костылят установкой внутренней памяти в кач-ве памяти по умолчанию, однако в CM такой пункт либо отсутсвует, либо спрятан.

**Comment by agent-007** [comment]
Соответственно, не работает и перенос приложений на карту SD. 

Лог:

E/Vold    (  244): Error creating imagefile (Read-only file system)
E/Vold    (  244): ASEC image file creation failed (Read-only file system)
W/Vold    (  244): Returning OperationFailed - no handler for errno 30
E/PackageHelper( 4827): Failed to create secure container smdl92555543.tmp
W/DefContainer( 4827): Failed to copy package at /data/app/com.google.android.apps.docs-1
W/DefContainer( 4827): java.io.IOException: Failed to create container smdl92555543.tmp
W/DefContainer( 4827):  at com.android.defcontainer.DefaultContainerService.copyPackageToContainerInner(DefaultContainerService.java:327)
W/DefContainer( 4827):  at com.android.defcontainer.DefaultContainerService.access$000(DefaultContainerService.java:67)
W/DefContainer( 4827):  at com.android.defcontainer.DefaultContainerService$1.copyPackageToContainer(DefaultContainerService.java:108)
W/DefContainer( 4827):  at com.android.internal.app.IMediaContainerService$Stub.onTransact(IMediaContainerService.java:60)
W/DefContainer( 4827):  at android.os.Binder.execTransact(Binder.java:446)

**Comment by divis1969** [comment]
карта уже использовалась на другом телефоне (или не этом билде)?
у меня есть подозрения, что проблемы с картой возникают только если она уже использовалась до этого.

**Comment by agent-007** [comment]
Карта использовалась, но проблема не в этом. Старый каталог Android оттуда убран.

**Comment by agent-007** [comment]
А ноги проблемы растут отсюда: http://review.cyanogenmod.org/#/c/97562/

**Comment by agent-007** [comment]
Это не значит, что там нужно брать патч :) А вот описание проблемы, которое к нему приложено, вполне может помочь.

**Comment by agent-007** [comment]
Собственно, локальный костыль для лечения выглядит так:

mount -t vfat -o rw,dirsync,nosuid,nodev,noexec,relatime,uid=1023,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro /dev/block/vold/179:129 /mnt/secure/asec

Пока попробую положить скрипт в /system/etc/init.d/ и пожыть с ним какое-то время, но в целом это нужно чинить по человечески. 

**UPD** **Не работает**

**Comment by divis1969** [comment]
Я думаю, что надо поправить значение переменной EXTERNAL_STORAGE.
Она сейчас определена в init.ssd.rc как /storage/emulated/legacy, а надо назначить ей /storage/sdcard1

Правда, проверить я это пока не могу, может быть вы попробуете?

**Comment by agent-007** [comment]
Ок, проверю.

**Comment by agent-007** [comment]
Докладываю. То ли у меня криво пересобирается boot, то ли замена значений вгоняет телефон в bootloop. 

Согласно   https://source.android.com/devices/storage/config-example.html#android_5_x_both, EXTERNAL_STORAGE как раз и должен смотреть в /storage/emulated/legacy 

Добрался до работы, и нормально разобрал ядро. 

```
export EXTERNAL_STORAGE /storage/emulated/legacy
export EMULATED_STORAGE_SOURCE /mnt/shell/emulated
export EMULATED_STORAGE_TARGET /storage/emulated
export SECONDARY_STORAGE /storage/sdcard1

```

Это правильно. Замена EXTERNAL_STORAGE на /storage/sdcard1 будет неверной, потому что:

EXTERNAL_STORAGE это внутренняя карта SD, которая живёт на той же памяти, что и система;
SECONDARY_STORAGE - внешняя карта SD, которую можно втыкать-вытыкать.

**Comment by agent-007** [comment]
Проблема с переносом установленных приложений на карту памяти вроде решилась.

https://android.googlesource.com/platform/system/vold/+/android-5.1.1_r35/main.cpp

`/* Only set this flag if there is not an emulated sd card */
            if (fs_mgr_is_noemulatedsd(&fstab->recs[i]) &&
                !strcmp(fstab->recs[i].fs_type, "vfat")) {
                flags |= VOL_PROVIDES_ASEC;
            }`

Соответственно:

`--- fstab.mt6735.orig  2016-03-24 10:22:13.000000000 +0300
+++ fstab.mt6735    2016-03-24 11:18:15.492370390 +0300
@@ -13,6 +13,6 @@

 #please add cip or persist on project fstab
 #/dev/block/platform/mtk-msdc.0/by-name/persist    /persist     ext4   noatime,nosuid,nodev,noauto_da_alloc,commit=1,nodelalloc   wait,check,autoformat
-/devices/mtk-msdc.0/11230000.MSDC0   auto      vfat      defaults        voldmanaged=sdcard0:emmc@intsd,noemulatedsd
-/devices/mtk-msdc.0/11240000.MSDC1  auto      vfat      defaults        voldmanaged=sdcard1:auto
+/devices/mtk-msdc.0/11230000.MSDC0   auto      vfat      defaults        voldmanaged=sdcard0:emmc@intsd,noemulatedsd,nonremovable
+/devices/mtk-msdc.0/11240000.MSDC1  auto      vfat      defaults        voldmanaged=sdcard1:auto,noemulatedsd
 /devices/platform/mt_usb                auto      vfat      defaults        voldmanaged=usbotg:auto

`
После этого внешняя карта автоматически монтируется в /mnt/media_rw/sdcard1 и /mnt/secure/asec, что формально является правильным. Приложения переносятся и не пропадают после перезагрузок. 

Не уверен, впрочем, что это действительно правильное решение. 

Установка из play market по прежнему не работает, с той же диагностикой.

**Comment by agent-007** [comment]
[boot.zip](https://github.com/divis1969/android_device_meizu_meilan2/files/187738/boot.zip)

**Итак, фактически есть две не связанных друг с другом ошибки.**
1. Невозможно установить некоторые приложения из Google Play (например, ABBYY Textgrabber)
2. Невозможно перенести установленные программы на карту SD 

Ошибка №1 лечится установкой [cgapps](https://github.com/cgapps/vendor_google), а не open gapps.

Ошибка №2 лечится установкой правильных флагов для vold 

[fstab.mt6735.patch.txt](https://github.com/divis1969/android_device_meizu_meilan2/files/187673/fstab.mt6735.patch.txt)

Исправленный образ ядра в аттаче ниже:

[boot.zip](https://github.com/divis1969/android_device_meizu_meilan2/files/187740/boot.zip)

**Comment by divis1969** [comment]
Переоткрою, закроем, когда фикс войдет в релиз.

Но вообще говоря, патч для fstab не очень понятен.
MSDC0 это, я так полагаю контроллер, который у нас работает с основной картой памяти. И там в качестве карты монтируется раздел intsd основной памяти (если я правильно это понимаю), которого нет.
Для MSDC1 тоже не очень понятно, noemulatesd как-то не очень к физическому устройству относится.

**Comment by agent-007** [comment]
Для того, чтобы переносить приложения на устройство, которое не умеет нормальных файловых систем ( карта SD с fat32 ), vold должен смонтировать fs на этом устройстве специальным образом. Специальность заключается в bind mount в /mnt/secure/asec, который делается на основании наличия флага внутри vold. А флаг, в свою очередь, выставляется на основании наличия опции noemulatesd в fstab.

Поэтому если мы имеем карту SD, то без noemulatesd перенести на неё что либо будет невозможно.

Внутренняя карта SD (EXTERNAL_STORAGE), несмотря на то, что она emulated, монтируется с noemulatesd. А внешняя (SECONDARY_STORAGE), которая не-emulated, без. Почему так сделано по умолчанию я не понимаю.

**Comment by divis1969** [comment]
Два вопроса:
1. На какую карту должен происходить перенос приложения? С измененным fstab перенос, действительно, работает, но, приложение не на sdcard1 переносится (во всяком случае, на ней я не наблюдаю следов приложения, которое переношу)
2. Бесплатных приложений нет, которые не устанавливаются?

**Comment by agent-007** [comment]
> На какую карту должен происходить перенос приложения?

На внешнюю карту SD. Следов не видно, потому что приложение лежит внутри /sdcard1/.android_secure. Следы видно в /mnt/secure/asec.

> Бесплатных приложений нет, которые не устанавливаются?

Не проверял. Думаю, любое приложение с android:installLocation="preferExternal" устанавливаться не будет.

**Comment by divis1969** [comment]
Ок, с переносом приложений вроде понятно стало, буду подбирать этот фикс в след. релиз.

С установкой не понятно. Я специально сделал приложение с android:installLocation="preferExternal". Оно вполне успешно устанавливается на sd card (правда через adb install).

Надо бы найти какое-то не платное приложение, я вряд ли буду у гуглоплея что-то покупать в тестовых целях :-)

**Comment by agent-007** [comment]
Достаточно включить фикс для переноса. Если он будет включен, и gapps будут
правильные, все проблемы с установкой из любых источников вылечатся. И
проблемы с переносом приложений - тоже вылечатся.

2016-03-28 13:59 GMT+03:00 divis1969 notifications@github.com:

**Comment by divis1969** [comment]
Проверьте, на v0.8.
Туда вошел ваш фикс (https://github.com/divis1969/android_device_meizu_meilan2/commit/f92046a312c208514b98b5ba503322694da3c9b5)

Хотя, я бы предпочел изучить эту проблему с opengapps (если она еще осталась).

**Comment by agent-007** [comment]
Resolved, fixed
