### ISSUE TITLE
Падает родной файловый менеджер при попытке зайти в настройки.

### ISSUE THREAD

**Issue by agent-007** [divis1969/android_device_meizu_meilan2#46]
Как воспроизвести:
1. Запустить менеджер файлов
2. Войти в настройки - основные настройки

**Comment by divis1969** [comment]
Багу надо бы на СМ заводить, 
Скорее всего неправильное форматирование ресурса для русского языка: 
`<string name="pref_disk_usage_warning_level_summary" formatted="false">Отмечать красным индикатор занятого места, если диск заполнен на <xliff:g id="level">%1$s</xliff:g> %</string>`
я думаю, знак %, который и вызывает ошибку. https://github.com/CyanogenMod/android_packages_apps_CMFileManager/blob/cm-12.1/res/values-ru/strings.xml#L308
Кстати, на бранче caf/cm-12.1 она то ли исправлена, то ли ее и не было (там слово "процентов")

Еще у болгар такой знак, вроде

**Comment by divis1969** [comment]
Создал https://jira.cyanogenmod.org/browse/CYAN-7627

**Comment by divis1969** [comment]
Подобрал последние изменения cm-12.1 - вроде теперь не падает.

**Comment by divis1969** [comment]
Закрою без подтверждения сабмиттера, поскольку у меня не падает больше
