### ISSUE TITLE
Всё равно не отправляются файлы по Bluetooth, поскольку требует пин код с 16 цифр

### ISSUE THREAD

**Issue by grozahn** [divis1969/android_device_meizu_meilan2#47]

**Comment by divis1969** [comment]
Должно быть пофикшено на v0.8
Проверьте, пожалуйста.

Коммит https://github.com/divis1969/android_packages_apps_Bluetooth/commit/596f2173df1a7f8edf4ba931f0d5a49303047408

**Comment by grozahn** [comment]
Всё работает, но вылазит иногда ошибка "Не удалось подключиться поскольку PIN  введён неправильно". Также не отправляются файлы с ПК: Xubuntu 14.04.4, а именно нет запроса на приём файла.

**Comment by divis1969** [comment]
1. Что за устройство в случае когда ошибка появляется?
2. До этого ПК и телефон были сопряжены? Эта ошибка похожа на ту, что я видел с другим телефоном на cm-12.1. Я пока еще только планирую ею заняться.

**Comment by grozahn** [comment]
Ошибка появляется только на ПК, может это кривость Blueman' а, от других устройств запрос приходит, сейчас на гноме протестирую и напишу.

**Comment by grozahn** [comment]
В общем это кривость Blueman, не нужно уже BT фиксить так как проблема не в прошивке, все равно собирался на гном переехать
