### ISSUE TITLE
Датчик холла

### ISSUE THREAD

**Issue by fadeevalan** [divis1969/android_device_meizu_meilan2#48]
Не работает датчик холла версия прошивки 0.7, ранее писали что в 0.5 пофиксили, но у меня чехлом не блокирует экран. Betta 5 и флайм 4 все отлично.

**Comment by divis1969** [comment]
Вы имеете ввиду проксимити?
на 0.7 есть инженерное меню, в котором, можно датчик откалибровать. Вы пробовали? После этого работает или все-таки нет?

**Comment by agent-007** [comment]
Датчик Холла это [датчик магнитного поля](https://en.wikipedia.org/wiki/Magnetometer#Hall_effect_magnetometer)

[Proximity sensor](http://thecodeartist.blogspot.ru/2011/01/proximity-sensor-on-android-gingerbread.html) (датчик приближения) обычно оптический. 

Работают они оба вроде, и открытие чехла будит телефон и включает экран. А вот при закрытии экран не выключается. Скорее всего, это связано с тем, что какое-нибудь событие просто не обрабатывается.

**Comment by divis1969** [comment]
в чехле магнит что-ли? я просто не пользуюсь чехлами...

**Comment by agent-007** [comment]
У меня вроде без магнита. Так что он, скорее всего, реагирует на датчик
освещённости.

**Comment by divis1969** [comment]
Т.е. достоверно никто не знает, что именно используется?
Если это датчик освещенности или проксимити, то этот сценарий должен воспроизводиться просто с поднесением руки. Но у меня, это не будит телефон.

**Comment by agent-007** [comment]
Точно неизвестно. Интернет говорит что в чехлах магнит. Разбирать чехол лень, а явно железки к нему не прилипают.

**Comment by divis1969** [comment]
Разбирать не надо.
Хотя и не очень понятно пока, что же за датчик имелся ввиду.
Все-таки, видимо, магнитный датчик. 
Какой-нито sensorbox показывает наличие магнитометра, который, возможно используется, в том числе и как датчик для чехла. 
Может быть, вы можете проверить как влияет на него чехол (в этом приложении)?

**Comment by agent-007** [comment]
Как то влияет, цифры по крайней мере меняются при приближении-удалении
крышки. Что с этим дальше делать, правда, не очень ясно.

2016-03-28 16:58 GMT+03:00 divis1969 notifications@github.com:

**Comment by divis1969** [comment]
Ок. Я поищу чехол и буду исследовать.
Телефон просыпается от чехла прямо "из коробки" или что-то еще где-то надо настроить?

**Comment by agent-007** [comment]
Я немного поковырял эти чехлы.

Закрытие крышки это событие "нажатие кнопки F11". Открытие - F12. Сообстветственно, если в xposed additions замапить клик F11 на power (при включенном экране), телефон будет блокироваться.

**Comment by divis1969** [comment]
Да, похоже, у этих эвентов еще есть аттрибут LID_SWITCH и они триггерят определенное поведение.
Но, скорее всего у меня одна из конфигурационных опций не включена и выключения не происходит.
Это зависит от вот этой переменной:
https://github.com/divis1969/android_frameworks_base/blob/cm-12.1/policy/src/com/android/internal/policy/impl/PhoneWindowManager.java#L1578

конфигурационная опция тут:
https://github.com/divis1969/android_frameworks_base/blob/cm-12.1/core/res/res/values/config.xml#L589

Надо ее в оверлее в true определить

**Comment by fadeevalan** [comment]
В x-posed присвоил ф11 power of, а вот при звонке не будит экран. По этому пришлось на ф12 end call ставить. В настройках отключил завершить звонок кнопкой питания.

**Comment by divis1969** [comment]
Должно быть пофикшено на v0.8 коммитом https://github.com/divis1969/android_device_meizu_meilan2/commit/a87c6a61fe8f39392e8b82b1531bdcc99303b4eb

Проверьте, пожалуйста

**Comment by agent-007** [comment]
Resolved, fixed.
