### ISSUE TITLE
The phone cannot register in the cellular network

### ISSUE THREAD

**Issue by divis1969** [divis1969/android_device_meizu_meilan2#5]

**Comment by janengelmohr** [comment]
I don't know if mobile data is already fixed, but you might have a look at this: https://github.com/visi0nary/android_device_elephone_p8000/commit/acef54db8cf65913c13b5c3645393a4ce14781c2

**Comment by divis1969** [comment]
Yes, I have it in https://github.com/divis1969/android_frameworks_opt_telephony/commit/c999cc5c51fa52a472d608757ead87f252e2c830

**Comment by divis1969** [comment]
The issue with some SIMs is fixed by https://github.com/divis1969/android_device_meizu_meilan2/commit/7e9e404f6f8e78966f8b85fbf0b16354d5afeae7

Considering this as fixed
