### ISSUE TITLE
CyanogenMod Screencast не поддерживается

### ISSUE THREAD

**Issue by Shady885** [divis1969/android_device_meizu_meilan2#51]
В плей маркете пишет, что не поддерживается устройством, хотя Screencast создан специально для СМ.
Пробовал ставить вручную, но при нажатия start ничего не происходит, хотя потом в галерее появляются видео, но телефон говорит типа не удалось воспроизвести видео!

**Comment by divis1969** [comment]
Я не нашел CM Screencast на маркете, можно ссылку?

**Comment by Shady885** [comment]
https://play.google.com/store/apps/details?id=com.cyanogenmod.screencast

**Comment by Shady885** [comment]
Скорее всего дело не в нашей прошивке, а в самом приложении, потому что на другом телефоне такая же беда. Лучше наверное закрыть багу!

**Comment by agent-007** [comment]
Лучше всё таки посмотреть,  чего этому скринкасту не хватает.
30 марта 2016 г. 18:33 пользователь "Shady885" notifications@github.com
написал:

**Comment by divis1969** [comment]
возможно это из той же оперы что и https://github.com/divis1969/android_device_meizu_meilan2/issues/26

Ну, кстати, ссылка у меня не работает

**Comment by Shady885** [comment]
Странно... У меня ссылка открывается через маркет и через браузер тоже!

**Comment by Shady885** [comment]
Я кажется понял. У меня открывает, потому что я когда-то давно уже ставил это приложения на СМ 10, а на самом деле приложения это уже удалили из маркета. А ребята из контакта тоже написали, типа несуществующий адрес!
Точно удалили...Последний раз приложения обновляли в 14 году, и последний комментарий был написан в 14 году!
