### ISSUE TITLE
Не работает OTG

### ISSUE THREAD

**Issue by snk26** [divis1969/android_device_meizu_meilan2#52]
При включении флешки по OTG она 5 раз моргает, но монтирование не происходит.

[Логи](https://github.com/divis1969/android_device_meizu_meilan2/files/196467/logcat.log.ZIP)

**Comment by divis1969** [comment]
Спасибо за логи.
Я вроде уже понял как фиксить и даже проверил это, на моей флешке работает.
В общем, надо вот тут https://github.com/divis1969/android_device_meizu_meilan2/blob/cm-12.1/overlay/frameworks/base/core/res/res/xml/storage_list.xml

добавить еще один сторадж:

```
<storage
    android:mountPoint="/storage/usbotg"
    android:storageDescription="@string/storage_usb"
    android:removable="true"
    android:maxFileSize="4096" />
```

включу этот фикс в следующий релиз.

**Comment by divis1969** [comment]
Исправлено в v0.9, коммит https://github.com/divis1969/android_device_meizu_meilan2/commit/39a0a5fe665432d6d0b09b7ad436f91a3977f98b

**Comment by divis1969** [comment]
Видимо, подтверждения от сабмиттера не должаться... Закрываю тогда.
