### ISSUE TITLE
Quick Restart does not work

### ISSUE THREAD

**Issue by erderbi** [divis1969/android_device_meizu_meilan2#58]
Selecting quick restart in the menu Advanced shutdown, the meizu gets caught.
V0.8

**Comment by mgeranimus** [comment]
Working good. Enabled through developer tools. Working good all variants. Restart from zero. Restart OS.restart to recovery.restart to bootloader. All works to me

**Comment by mgeranimus** [comment]
Do factory reset. And flash super su. For example. You can enable root option for programs through drveloper tools. Annd you may try install supersu through play market and then open app and press instal normal. Restart device.For me it worked. I reflashed several times.

**Comment by divis1969** [comment]
@erderbi , what do you mean by "quick restart" ? I have 4 options when advanced reboot is enabled: Reboot, Soft Reboot, Recovery, Bootloader.

**Comment by divis1969** [comment]
There is no feedback from submitter for 24 days. Closing the issue
