### ISSUE TITLE
Не работает A2DP профиль Bluetooth

### ISSUE THREAD

**Issue by grozahn** [divis1969/android_device_meizu_meilan2#61]

**Comment by divis1969** [comment]
С каким девайсом не работает? Тест опишите, пожалуйста.

**Comment by grozahn** [comment]
С ПК на линуксе (Antergos Linux). Подключаюсь я некоторое время есть подключение но нет звука, а потом вовсе отключается

**Comment by divis1969** [comment]
С этой багой https://github.com/divis1969/android_device_meizu_meilan2/issues/47 никак не связано?
Я не совсем понимаю тест, вы с компа на телефон звук играете или наоборот? или еще что?

**Comment by agent-007** [comment]
с телефона на bt колонку звук играется нормально, а это вроде a2dp и есть.
поэтому было бы неплохо видеть логи bluez с компьютера с linux.

2016-04-06 14:03 GMT+03:00 divis1969 notifications@github.com:

**Comment by divis1969** [comment]
@grozahn, опишите вашу проблему поподробнее, а то бага есть, а что да как - непонятно.

**Comment by divis1969** [comment]
Видимо, подробностей не дождусь... Закрою, чтобы глаза не мозолила
