### ISSUE TITLE
Не работает гироскоп

### ISSUE THREAD

**Issue by grozahn** [divis1969/android_device_meizu_meilan2#63]
AIDA64 в пункте датчики не видит гироскоп

**Comment by divis1969** [comment]
на стоке он есть?

**Comment by grozahn** [comment]
Не могу знать точно, но он работал

**Comment by agent-007** [comment]
Он и на CM есть. Droid info его показывает, и даже показания датчика
меняются в зависимости от ориентации устройства.

**Comment by grozahn** [comment]
Gyroscope: Not supported

**Comment by divis1969** [comment]
Последний коммент что означает?
Sensorbox показывает гироскоп, но это программный гироскоп, т.е. по сути просто ориентация в пространстве на основе других датчиков.
Поэтому и был вопрос про наличие датчика на стоке.

**Comment by agent-007** [comment]
Другого гироскопа не завезли. И на стоке тоже.

**Comment by divis1969** [comment]
@grozahn , поясните, пожалуйста, что означает это "но он работал"? AIDA64 на стоке показывал гироскоп?

**Comment by divis1969** [comment]
на моем телефоне с v0.10 есть и гироскоп (software gyroscope) и магнетометр (MAGNETOMETER).
Видимо какая-то есть зависимость на железо. 
Если можете - снимите багрепорт (отчет об ошибке) сразу как телефон загрузится. Я подозреваю, что бага 53 с этой связана (и более того, именно, отсутствие магнетометра обуславливает отсутствие программных датчиков, типа гироскопа).

**Comment by divis1969** [comment]
Попробуйте v0.12, там был фикс для определенного типа датчика
https://github.com/divis1969/android_device_meizu_meilan2/commit/94ef726ee8cacc8687c7bd06f25ed20af9017d0b
https://github.com/divis1969/android_vendor_meizu_meilan2/commit/16db533987d20ad3ab98202257de075ad6358406
