### ISSUE TITLE
Замените приложение камеры из Flyme на Cyanogen Camera. Или вообще сток приложение CM 12.1 замените на Cyanogen Camera

### ISSUE THREAD

**Issue by grozahn** [divis1969/android_device_meizu_meilan2#67]

**Comment by divis1969** [comment]
Хотя бы сссылку можно на эту Cyanogen Camera? Она из маркета?

2016-05-12 0:26 GMT+03:00 grozahn notifications@github.com:

**Comment by grozahn** [comment]
http://4pda.ru/forum/index.php?showtopic=612022&st=40#entry38333906

**Comment by grozahn** [comment]
Лучше заменить стандартную камеру на Cyanogen Camera - у неё скудный функционал

**Comment by divis1969** [comment]
Разве просто нельзя установить ее из маркета? https://play.google.com/store/apps/details?id=com.cyngn.cameranext#

**Comment by grozahn** [comment]
Как-то не очень иметь два приложения камеры, а морозить сток бессмысленно.
