### ISSUE TITLE
Не работает блютуз гарнитура

### ISSUE THREAD

**Issue by dkova** [divis1969/android_device_meizu_meilan2#70]
Добрый день. Гарнитура коннектится, галочка HSP/HFP стоит, но звук разговора всё равно идёт через динамик.

**Comment by skillfinc** [comment]
V0.11,BT гарнитура (Nokia bh-102).Гарнитура коннектится, галочка HSP/HFP стоит, но звук разговора всё равно идёт через динамик.

**Comment by divis1969** [comment]
В v0.12 вошел фикс для гарнитуры, проверьте пожалуйста
https://github.com/divis1969/android_hardware_libhardware/commit/87fd6bbc4bb83a611b81f050d7385d40bbcd11ae
https://github.com/divis1969/android_packages_apps_Bluetooth/commit/b35117845d19cac1abd18889f96f1d348ef5f4f8
https://github.com/divis1969/android_external_bluetooth_bluedroid/commit/6b870b597c5687107f1684da0867b5fe389402bf

**Comment by divis1969** [comment]
Assuming it is fixed.
