### ISSUE TITLE
Missing unmount otg storage

### ISSUE THREAD

**Issue by stubbornboy** [divis1969/android_device_meizu_meilan2#71]
Hi..recently i used this cm 12 build (0.10 and 0.11) for m2, but as always (in my previous devices to) on cm 12 build, the dev maybe forget to merge resourse to have enable unmount option for otg storage on storage option so i get very difficult or maybe cannot unmount usb/otg storage when i plug it in. When i forced to unplug usb device will not recognise the usb or other usb until we restart devices.
Maybe you can fix this with ota update or next build coz i really love to used this cm built rather than meizu os.
For information this is the resource to merge to fix usb/otg unmount option 
http://review.cyanogenmod.org/#/c/63299/
Thank you for your built dev.

**Comment by dev-harsh1998** [comment]
Same here ;_;

**Comment by divis1969** [comment]
This code is outdated a little bit. All the support is already present in the code we use, but porting is not complete.
More specifically, Settings app checks the persist.sys.isUsbOtgEnabled property, and do not show any UI  if it is not present or is false.
There is no any component that initialize the property, so I suppose the vendor (i.e. me for cm port) should create/set it.
I'll include the fix into next release.
Meantime, you can manually set this property to true:
`adb shell setprop persist.sys.isUsbOtgEnabled true`

**Comment by divis1969** [comment]
Should be fixed in v0.12. Could you please test?
https://github.com/divis1969/android_device_meizu_meilan2/commit/9630489cc77adfab8aa7c0f48aad068ab6451d40

**Comment by stubbornboy** [comment]
So sorry icant test it..already move to xiaomi devices.but the solution yo give me is working. Im sure is already fix on your latest build.thank in advance

**Comment by divis1969** [comment]
Ok, closing it
