### ISSUE TITLE
GPS not working

### ISSUE THREAD

**Issue by ivribalko** [divis1969/android_device_meizu_meilan2#73]
Hello there,

GPS doesn't seem to work. When switching to Location->Device only mode no app can figure out my location at all. High accuracy mode works but positions apps like Google Maps and Pokemon GO poorly. GPS Test app says '10-20 In View -- 0 In Use'. Got the latest version - meilan2-cm-12.1-v0.11.

**Comment by ivribalko** [comment]
GPS Status & Toolbox app stuck at 'Looking for GPS location...' status. Can I give you something that might shed light on this issue?

**Comment by ivribalko** [comment]
Tried 'Faster GPS' app to no success. Also tried to remove mtkgps.dat in /data/misc

Verified my gps.conf is
NTP_SERVER= ru.pool.ntp.org
XTRA_SERVER_1=http://xtra1.gpsonextra.net/xtra.bin
XTRA_SERVER_2=http://xtra2.gpsonextra.net/xtra.bin
XTRA_SERVER_3=http://xtra3.gpsonextra.net/xtra.bin
SUPL_HOST=supl.google.com
SUPL_PORT=7276

**Comment by ivribalko** [comment]
Aight, something (leaving phone alone, moving to the window and previous various actions) let me to hook onto like 6 out of 14 satellites. Gonna test tomorrow.

**Comment by grozahn** [comment]
У меня GPS работает прекрасно, даже лучше чем на Flyme 5. Также в GPS Test пишет - "3D Fix", а на Flyme 5 - "No Fix". Я считаю, что тему можно закрывать.
P.S. Pokémon GO также работает идеально.

**Comment by ivribalko** [comment]
Странности есть, у меня редко приходит сигнал от GPS в приложениях, и единственный верный способ - это запустить GPStest, он точно подключается и сразу. Я еще посмотрю немного.

**Comment by divis1969** [comment]
А в настройках -> местоположение что выставлено?

**Comment by ivribalko** [comment]
High accuracy в основном. Device only мне местоположение редко обновляет.

**Comment by ivribalko** [comment]
Закрою пожалуй, вроде все неплохо. Спасибо вам за прошивку.
