### ISSUE TITLE
CPU always high, no deep sleep

### ISSUE THREAD

**Issue by sergibaljin** [divis1969/android_device_meizu_meilan2#76]

**Comment by sergibaljin** [comment]
The gravity detector is used to check if the phone is docked on or not. If the gravity detector doesn't work (see issue #74) there may be problems? Attached the output of "dumpsys power"
[dumpsyspower.txt](https://github.com/divis1969/android_device_meizu_meilan2/files/392684/dumpsyspower.txt)

The CPU is constantly at 1040Mhz and never in deep sleep, even though no wakelock was found.

**Comment by sergibaljin** [comment]
Deep sleep OK with version v0.9

I close the defect as there is a good workaround. The flyme gesture module would be the suspect for the wakelock/high frequency CPU.

**Comment by divis1969** [comment]
Actually, I'm suspecting proximity sensor on some devices causes this.
Here ( https://drive.google.com/file/d/0Bwzrxcf3P6N6Qkc3WktDSTdUczQ/view?usp=sharing ) is the build based on v0.11 with the only change: removed proximity initialization introduced by v0.10. You can try it.

**Comment by sergibaljin** [comment]
Thanks a lot.
Your suspicions were correct, this build works really well. It's frustrating how this problem is so case-dependent. I have reported the defect also for Flyme without any real answer.
I hope I can return the favor done for us incautious buyers.

**Comment by divis1969** [comment]
I believe the issue can be related to the hardware differences between devices. Perhaps software should match the device (as you probably know there are various Meizu stock images targeted to different markets).
