### ISSUE TITLE
Need your help！

### ISSUE THREAD

**Issue by Jlsmily** [divis1969/android_device_meizu_meilan2#77]
I'm porting CyanogenMod Android to meizu m2 note , it has similar with elephone_p8000 ,but I don't
know how to do that ,can you give me some guide? Thank you,please!

**Comment by divis1969** [comment]
Well, it's too generic question. Can you be more specific?
In general, porting requires some background: you should be familiar with linux (as a user/developer), c/c++ and Java, git (version control), android processed (getting a source, building, running on a device, see http://source.android.com/source/requirements.html, for example, debugging).

Do you have this background? If not, it would be a nightmare for me to guide you in this process.
If you have more detailed question, please use my email (you can find it in the commits in my repositories) to communicate me.
