### ISSUE TITLE
Deep sleep with version 0.12

### ISSUE THREAD

**Issue by sergibaljin** [divis1969/android_device_meizu_meilan2#82]
As in the defect #76 there is something keeping the CPU active.
I have tried:

persist.devcontrol.proximity=-1
persist.devcontrol.proximity=0
persist.devcontrol.proximity=458 

in the build.prop without success.

**Comment by divis1969** [comment]
Could you please collect the bugreport immediately after reboot?
So,
1. Set the property
2. Reboot the phone
3. Start bugreport collection as soon as boot finished.

**Comment by divis1969** [comment]
BTW, did you reboot the phone once you've set the property? The property is read only once the phone boots

**Comment by sergibaljin** [comment]
Yes, I restarted the phone every time. What log would you like? the one generated by the "take bug report" function is OK (I mean Android original bug report Android)?

**Comment by divis1969** [comment]
yes, original bugreport is ok. Alternatively you can start logging from PC with adb:
`adb logcat -v threadtime -b all > logcat.log`
and terminate it with Ctrl-C once the phone booted to lock/idle screen

**Comment by sergibaljin** [comment]
[reports.zip](https://github.com/divis1969/android_device_meizu_meilan2/files/477238/reports.zip)

Here the three reports. I hope I didn't mess up things, but the proximity is always the same.

**Comment by sergibaljin** [comment]
Hi
the deep sleep problem is OK now, as long as I set the it to 0 (no initialization). I guess I made ome stupid mistake earlier. I will close the issue, please do blame me.
