### ISSUE TITLE
mback issue

### ISSUE THREAD

**Issue by caesarw** [divis1969/android_device_meizu_meilan2#83]
Sorry, i cant speak Russian. So i write in English.

I flashed your CM ROM, and i appreciate your work very much. But i found a issue, that is, the "mback" key function cant be used. When in Flyme OS, the mback key functions as the back key and the home key. When you touch it, it functions as the back key, when you click it, it funtions as a home key. But in CM ROM, when you want to use the key as "home key"(of course you click it) then it will first go back and then go to home screen, instead of going to home screen directly. The user experience is a bit bad. I looked for the mback key solution in Google, and i found an XDA ROM maker solved the problem. Sorry, i cant find the post right now, but i really hope that you can help solve the problem! I know enabling virtual on screen keys can solve the problem, but i think it might take up too much space on screen.,

Thank you very much for your help!

**Comment by ghost** [comment]
Meep, meep, M2 Note dev here !
https://github.com/Moyster/android_device_meizu_m2note/blob/cm-12.1/keyhandler/src/com/cyanogenmod/settings/device/KeyHandler.java#L259

(this might need a bit of adaptation to fit on meilan2)
(edit: link was not pointing the correct line)

**Comment by caesarw** [comment]
Thank you very much for you code! Looking forward to fix the problem with your code!

**Comment by caesarw** [comment]
Basically, the mback key is used like this: touch for "back", press for "home".
In the official Flyme OS, when you touch it, it functions as a back key. When you press it, it will simply go directly to home screen.
But in CM, when you touch it, it functions as a back key, too. When you press it, it will first go back and then go to home screen. It's so annoying that I changed back to Flyme OS. Hope to fix it really quick cause I really want to use CM.

**Comment by ghost** [comment]
Don't worry divis will answer soon enough, we all have a life you know ? 💋
