### ISSUE TITLE
No data connection after WiFi disconnect

### ISSUE THREAD

**Issue by ygorigor** [divis1969/android_device_meizu_meilan2#86]
If mobile data connection and WiFi are enabled, after WiFi is disconnected the data through mobile connection not working.

**Comment by divis1969** [comment]
Which version do you use? Is it cm-12.1 or cm-14.0?

**Comment by ygorigor** [comment]
cm-12.1 v0.13

**Comment by ygorigor** [comment]
Usually it happens in the morning after I leave home and disconnect WiFi. 
This notification "restricted access changed - data service blocked" shows every morning.

**Comment by dev-harsh1998** [comment]
that issue is Due to your service provider may the the bands have switched cause of low network coverage or so if you want more details please consider dropping a radio logcat

**Comment by ygorigor** [comment]
Maybe, but on Flyme is all OK

**Comment by EarsKilla** [comment]
have this issue sometimes too. idk how to catch and logcat it. it can appears after "bad mobile network band" (like edge or no-signal). if i find place with bad mobile internet, i'll try to not forget logcat this issue

**Comment by ygorigor** [comment]
It's a carrier related issue

**Comment by EarsKilla** [comment]
soo. if this carrier's related issue, why this not fixes after toggling fly mode? 🤔
and switching bands too long (eg. lte to hspa and back). but on flyme os all working fine 🤔🤔
