### ISSUE TITLE
Fail to download update

### ISSUE THREAD

**Issue by perqin** [divis1969/android_device_meizu_meilan2#89]
I can check for updates, but after tapping download button, a notification comes reading "Unable to download the update file".

**Comment by divis1969** [comment]
Are you using cm-14.0 or cm-14.1?
The OTA is ported to cm-14.1-meilan2-v0.2
Commit
https://github.com/divis1969/android_packages_apps_CMUpdater/commit/325d44fd57be5693a7409982b7c43513ac7152d0

**Comment by perqin** [comment]
I was using cm-14.0 when facing this issue. Now I've already flashed cm-14.1-v0.2 and the updater works. Sorry for disturb and thanks for your works, have a nice day!
