### ISSUE TITLE
[CM-14] Hotspot can't be detected

### ISSUE THREAD

**Issue by arief20** [divis1969/android_device_meizu_meilan2#95]
Hotspots can be turned on, but can not be detected by other devices

**Comment by divis1969** [comment]
Which version do you use?

**Comment by arief20** [comment]
CM14 v.03

**Comment by arief20** [comment]
What would you fix?

**Comment by divis1969** [comment]
The issue should be fixed in cm-14.1-meilan2-v0.2
Commit
https://github.com/divis1969/android_system_netd/commit/fa9c62a09a025e620db540dff726b74b195586f6
