### ISSUE TITLE
How to bypass the setup wizard?

### ISSUE THREAD

**Issue by perqin** [divis1969/android_device_meizu_meilan2#96]
Hi, I've just flashed CM 14.0 v0.3 to my m2 mini and boot the device without a sim card. However it keeps checking info. I've connected to a WiFi with Internet access. Is it possible to skip the setup wizard without a sim card? Thanks.

**Comment by arief20** [comment]
I have a solution, please flash the Google Apps (GAPPS) after booting (up on the homescreen)

**Comment by perqin** [comment]
@arief20 Hi, could you please explain in detail? How to flash gapps "after booting"?

**Comment by perqin** [comment]
Guys, I finally bypassed the CM setup wizard. First flash OpenGapps to get Google's setup wizard, and then connect phone to your PC and use adb to disable CM's setup wizard(simply killing the app is not enough as it always restarts):

```
# pm disable com.cyanogenmod.setupwizard
```
