### ISSUE TITLE
sorry if disturbed

### ISSUE THREAD

**Issue by alfadly** [divis1969/android_device_meizu_meilan2#98]
Hi
I have problem in custrom rom CM 12.1 in meizu m2 note
"maybe" problem in band network, if go to MTK Engginer and click  Network Selecting directly force stop “Unfortunately the Process.com.android.phone Has Stopped” and bsotelephonydevtool can't click + showing
I discussion and message team port CM 12.1 meizu m2 note nothing solution :/
maybe Mr. Divis 1969 can help me for tutorial how to fix this problem because my sister use m2 mini and no problem in "Network Selecting" at ROM CM 12.1 and I use meizu m2 note use CM 12.1 go to Network Selecting in MTK engginer directly force stop :+1: 
I had wanted to send a message to Mr. Divis 1969 via 4pda but I am confused in registering the forum

Thank you :)

**Comment by divis1969** [comment]
Can you collect the log or bugreport? If so, send it to me (divis1969@gmail.com)
