### ISSUE TITLE
BTS connection (RIL connection) is loosing from time to time

### ISSUE THREAD

**Issue by Szymaniuk** [divis1969/android_device_meizu_meilan2#99]
First of all - great job with CM 12.1, working perfectly!
I've just moved a few days ago into CM 14.1, and I got some issue with BTS connection (RIL connection). It's just lloosing from time to time - without any reason.
It's dropping sometimes during the call - after a few minutes/seconds.
It's dropping while using LTE network connection.
It's dropping while using WiFi.
It's just dropping from time to time - status bar icon of BTS connection is just "empty" (like without connection) during this dropping.
It's "starting up" after a few seconds of lost connection - it's 100% independent of BTS/mobile provider.

**Comment by ygorigor** [comment]
You have to disable location in Settings

**Comment by Szymaniuk** [comment]
Already switched to 12.1.
Can't wait for fix for that and camera, that would be great.

Thanks again for you contribution and work 👍 and sorry for spam here :x

**Comment by divis1969** [comment]
This issue should be fixed in cm-14.1-meilan2-v0.2
Commits
https://github.com/divis1969/android_device_meizu_meilan2/commit/be52a68e2dad285ed7e4d290c993536a55801b05
https://github.com/divis1969/android_vendor_meizu_meilan2/commit/14f8abfe3204fb3221b6c6be4683de2e758fccd3

**Comment by Szymaniuk** [comment]
Great!!!
Will check that today and let here know about the result.
Thanks in advance!

**Comment by Szymaniuk** [comment]
Works like a charm!
